# Generated by Django 4.1.1 on 2022-09-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
